version: "3.9"
services:
  ml-service:
    build: ./ml-service
    ports:
      - "8000:8000"
  middleware:
    build: ./middleware
    ports:
      - "8080:8080"
    environment:
      - ML_BASEURL=http://ml-service:8000
    depends_on:
      - ml-service
