name: CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build-ml-service:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ml-service
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: python -m pytest || echo "TODO: add tests"
      - run: docker build -t ml-service:ci .

  build-middleware:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: middleware
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - run: mvn -q -e -DskipTests package
